import { Rarity } from "./gachaData";

export interface AvatarEncyclopediaEntry {
  id: string;             // e.g. "CHRA_001" or "EQ_LADIES_001"
  gachaItemId: string;    // matching id in gacha items
  name: string;           // Character / Equipment name
  title: string;          // Catchy title / epithet
  rarity: Rarity;
  gachaName: string;      // Source gacha name
  gachaTabId: "rich_ladies" | "rich" | "rich2" | "rich_ladies_equipment" | "rich_equipment";
  seriesId: "ladies" | "rich1" | "rich2" | "ladies_eq" | "rich_eq";
  seriesName: string;     // Series display name
  icon: string;           // Image asset URL
  story: string;          // Rich flavor text (150-300 chars)
  type?: "avatar" | "equipment";
  category?: "weapon" | "shield" | "head" | "wings" | "accessory";
}

export const avatarEncyclopediaList: AvatarEncyclopediaEntry[] = [
  // ==========================================
  // 🌸 ふわふわガチャ♡ シリーズ (17体)
  // ==========================================
  {
    id: "CHRA_001",
    gachaItemId: "avatar_ladies_スイーツガンナー",
    name: "スイーツデコガンナー",
    title: "甘美なる弾雨の狙撃手",
    rarity: "神レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/神レア_スイーツデコガンナー.webp",
    story: "魔法菓子店「シュクレ・ドゥ」の天才パティシエにして、お菓子の魔力を銃弾に変える凄腕スナイパー。普段は苺タルトのデコレーションに命をかける心優しい少女だが、仲間やお菓子を粗末にする悪党には容赦なく甘く危険なキャンディバレットを撃ち込む。その銃口から放たれる弾丸は、悪の心を蕩かして改心させるという。"
  },
  {
    id: "CHRA_002",
    gachaItemId: "avatar_ladies_ヒツジ魔導士",
    name: "夢見るヒツジの魔導士",
    title: "星夜を導く安らぎの賢者",
    rarity: "神レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/神レア_夢見るヒツジの魔導士.webp",
    story: "星座の羊毛から紡がれた魔法のパジャマを纏い、星空の夢界を護る高位魔導士。手にしたランタンは眠れぬ子どもたちに幸福な夢を灯す導きの光。少しおっとりとした性格で、魔法を唱えながら自分自身がうとうと眠ってしまうのがたまに瑕だが、その眠りの結界は古の魔王の呪いすらも穏やかな安らぎへと変えてしまう。"
  },
  {
    id: "CHRA_003",
    gachaItemId: "avatar_ladies_花ヒーラー姫",
    name: "花のヒーラー姫",
    title: "百花繚乱の慈愛姫",
    rarity: "神レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/神レア_花のヒーラー姫.webp",
    story: "精霊の森の奥深くに栄える花園の国「フローリア」の第一王女。生まれながらに万物を癒やす花の魔力を宿し、彼女が歩いた足跡には満開の百合と薔薇が咲き誇る。旅の途中で傷ついた冒険者たちを無償で癒やし、笑顔を届ける姿から「戦場の白き奇跡」と称えられている。頭のティアラは初代花の女王より受け継いだ秘宝。"
  },
  {
    id: "CHRA_004",
    gachaItemId: "avatar_ladies_キラキラ星踊り子",
    name: "キラキラ星の踊り子",
    title: "天の川を駆ける星辰舞姫",
    rarity: "超激レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/超激レア_キラキラ星の踊り子.webp",
    story: "夜空に流れる無数の星屑を集めて仕立てられたドレスを纏う天界の舞姫。彼女のステップは夜空の星座を動かし、見る者すべての心に勇気と希望の光を満たす。祭りや祝祭の夜にだけ地上に降り立ち、誰よりも華麗に宙を舞う。そのリボンには流れ星の軌跡が宿っており、触れた者に小さな幸運をもたらすと言われている。"
  },
  {
    id: "CHRA_005",
    gachaItemId: "avatar_ladies_天使聖騎士",
    name: "天使の羽根の聖騎士",
    title: "天翔ける白銀の守護翼",
    rarity: "超激レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/超激レア_天使の羽根の聖騎士.webp",
    story: "天空の聖域を守護する若き女騎士。純白の聖翼と黄金の甲冑を纏い、弱き者を脅かす魔物たちに毅然と立ち向かう。厳格な騎士道精神の持ち主だが、可愛い小鳥やスイーツには目がなく、パトロールの合間にこっそりカフェに立ち寄るのが日課。掲げた聖剣は天の光を宿し、邪悪な闇の波動を一太刀で浄化する。"
  },
  {
    id: "CHRA_006",
    gachaItemId: "avatar_ladies_宝石精霊使い",
    name: "宝石の精霊使い",
    title: "輝石と語らう地底の乙女",
    rarity: "超激レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/超激レア_宝石の精霊使い.webp",
    story: "地底深くに眠る宝石鉱脈に宿る精霊たちと心を通わせる神秘の少女。ルビーやサファイア、エメラルドの原石を使い、光と大地の魔導術を自在に操る。身につけている宝石たちは彼女の親友であり、危険が迫ると自ら光の盾となって彼女を守護する。普段は鉱石の美しさを探求する学者肌だが、戦いでは凛々しい表情を見せる。"
  },
  {
    id: "CHRA_007",
    gachaItemId: "avatar_ladies_白猫拳闘士",
    name: "白猫のモフモフ拳闘士",
    title: "純白の毛並み持つ怪力闘姫",
    rarity: "超激レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/超激レア_白猫のモフモフ拳闘士.webp",
    story: "モフモフの肉球グローブを装着した獣人族の格闘少女。愛らしい見た目と軽やかな身のこなしからは想像もつかないほどの怪力を誇り、巨大な岩石をも一撃で粉砕する。勝負事と昼寝が大好きで、「強くて可愛いのが一番無敵にゃ！」が口癖。彼女のパンチを受けた者は、あまりのモフモフ感に戦意を喪失してしまうらしい。"
  },
  {
    id: "CHRA_008",
    gachaItemId: "avatar_ladies_バラの舞踏騎士",
    name: "バラの舞踏騎士",
    title: "真紅の棘持つ華麗なる剣士",
    rarity: "激レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/激レア_バラの舞踏騎士.webp",
    story: "王都の社交界で最も華麗と噂されるレイピアの達人。真紅の薔薇をモチーフにしたドレスアーマーに身を包み、舞踏会でワルツを踊るかのように優雅に剣を振るう。貴族の悪政や不義を許さず、夜には義賊として市井の人々を助ける一面も持つ。彼女の剣先から放たれる薔薇の花弁は、敵の武器だけを的確に弾き飛ばす。"
  },
  {
    id: "CHRA_009",
    gachaItemId: "avatar_ladies_ラベンダー召喚士",
    name: "ラベンダーの召喚士",
    title: "香風薫る紫苑の幻獣使い",
    rarity: "激レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/激レア_ラベンダーの召喚士.webp",
    story: "紫に煙るラベンダー畑で育った魔導召喚士。鎮静と調和のハーブ魔法を極めており、香りに誘われた森の幻獣たちを味方として召喚する。争いを好まない穏やかな性格で、彼女の周囲には常に心地よい香りと温かな風が漂う。手にした古文書には、太古の聖獣たちと交わした友情の誓約が記されている。"
  },
  {
    id: "CHRA_010",
    gachaItemId: "avatar_ladies_月星の暗殺者",
    name: "月と星の暗殺者",
    title: "宵闇に潜む星影の刃",
    rarity: "激レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/激レア_月と星の暗殺者.webp",
    story: "新月の夜にのみ姿を現す星辰暗殺ギルドの若きエリート。夜空に溶け込む濃紺のマントと三日月の短剣を携え、音もなく悪の要人を討ち果たす。冷徹なプロフェッショナルを装っているが、実は寂しがり屋で夜空の月に向かって独り言を呟くのが癖。星明かりを足場にして空中を音もなく跳躍する特殊技能を持つ。"
  },
  {
    id: "CHRA_011",
    gachaItemId: "avatar_ladies_ビーストテイマー",
    name: "ひまわりのビーストテイマー",
    title: "陽だまりの心優しき獣使い",
    rarity: "レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/レア_ひまわりのビーストテイマー.webp",
    story: "太陽の光をたっぷり浴びて咲く向日葵のように明るい少女。どんな獰猛な魔獣でも一瞬で手懐けてしまう不思議なオーラを持ち、サバンナや平原の動物たちと大の仲良し。いつも笑顔で前向きな彼女の存在は、過酷な冒険の旅における最高のムードメーカー。トレードマークのひまわり髪飾りは元気の源。"
  },
  {
    id: "CHRA_012",
    gachaItemId: "avatar_ladies_ピンク魔法使い",
    name: "ピンクの魔法使い見習い",
    title: "桃色魔力溢れる元気娘",
    rarity: "レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/レア_ピンクの魔法使い見習い.webp",
    story: "王立魔法アカデミーの初等部に通う元気いっぱいの見習い魔女。ピンク色の魔法が大好きで、何でもハート型に変えてしまう癖がある。呪文の詠唱を間違えてケーキを爆発させる失敗も多いが、誰にも真似できない規格外の魔力ポテンシャルを秘めており、大賢者からも密かに将来を期待されている。"
  },
  {
    id: "CHRA_013",
    gachaItemId: "avatar_ladies_マカロン重戦士",
    name: "マカロン色の重戦士",
    title: "甘き装甲の鉄壁ガーディアン",
    rarity: "レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/レア_マカロン色の重戦士.webp",
    story: "パステルカラーのキュートな特注重装甲を纏った重戦士。パステルカラーの愛らしい外見とは裏腹に、自分よりも大きな大盾を軽々と操り味方への攻撃をすべて受け止める前線の鉄壁。美味しいスイーツを食べるために過酷な筋力トレーニングを欠かさず、装甲の強度はミスリル鉱石に匹敵する。"
  },
  {
    id: "CHRA_014",
    gachaItemId: "avatar_ladies_ミント風使い",
    name: "ミントグリーンの風使い",
    title: "清涼なる風翔ける精霊術士",
    rarity: "レア",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/レア_ミントグリーンの風使い.webp",
    story: "爽やかな高原の風を司る精霊術士。ミントグリーンの軽やかなローブをまとい、疾風に乗って大地を駆け抜ける。彼女が起こす清涼な風は仲間の疲労を吹き飛ばし、移動速度を格段に向上させる。いたずら好きで、風を使って旅人の帽子を飛ばしてはからからと無邪気に笑っている。"
  },
  {
    id: "CHRA_015",
    gachaItemId: "avatar_ladies_ロップイヤー騎士",
    name: "イチゴチョコのロップイヤー騎士",
    title: "跳躍する愛らしき兎騎士",
    rarity: "ノーマル",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/ノーマル_イチゴチョコのロップイヤー騎士.webp",
    story: "垂れ耳がチャームポイントのウサギ獣人族の騎士見習い。イチゴチョコをイメージした特製アーマーを誇らしげに着こなし、小さな木剣を手に正義のために駆け回る。足の速さと跳躍力は大人顔負けで、危機に陥った仲間のもとへ一番乗りで駆けつける勇敢な心の持ち主。大好物はイチゴ味の金平糖。"
  },
  {
    id: "CHRA_016",
    gachaItemId: "avatar_ladies_マーメイド",
    name: "マーメイドの歌姫",
    title: "波間を揺らす蒼海のソプラノ",
    rarity: "ノーマル",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/ノーマル_マーメイドの歌姫.webp",
    story: "碧い珊瑚礁の海で生まれ育った人魚の少女。彼女の透き通るような歌声は荒れ狂う嵐の海を鎮め、航海者たちに無事の帰還を約束する。陸の世界の文化に強い興味を持っており、水魔法で足元を浮遊させながら人間の街を散策するのがお気に入りの冒険。貝殻の髪飾りは母からのお守り。"
  },
  {
    id: "CHRA_017",
    gachaItemId: "avatar_ladies_エルフ弓使い",
    name: "星屑のエルフの弓使い",
    title: "銀星を射落とす森の狩人",
    rarity: "ノーマル",
    gachaName: "🌸 ふわふわガチャ♡",
    gachaTabId: "rich_ladies",
    seriesId: "ladies",
    seriesName: "ふわふわファンタジー",
    icon: "/avatars/ladies/ノーマル_星屑のエルフの弓使い.webp",
    story: "星明かりが降り注ぐ銀の森を守るエルフの狩人。夜空の星屑を矢じりに宿した特製の弓を用い、百発百中の命中精度を誇る。物静かで自然を深く愛し、森の木々や小鳥たちの声を聞き分けることができる。彼女の放つ光の矢は暗闇を照らす松明となり、迷える旅人の進むべき道を指し示す。"
  },

  // ==========================================
  // 💎 リッチガチャ1 シリーズ (10体)
  // ==========================================
  {
    id: "CHRA_018",
    gachaItemId: "rich_dragon",
    name: "神竜",
    title: "創世の天空を統べる古竜",
    rarity: "神レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/dragon.webp",
    story: "世界の始まりより天空を統べる至高の古竜。金色の瞳には万物の真理が映り、その咆哮は大地を震わせ雲海を裂く。世界の均衡が崩れそうになった時のみ姿を現し、神聖なるブレスで邪悪を焼き払う。太古の時代から幾多の英雄に試練と加護を与えてきた伝説の守護神。"
  },
  {
    id: "CHRA_019",
    gachaItemId: "rich_princess",
    name: "プリンセス",
    title: "輝く帝国の愛されし皇女",
    rarity: "神レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/cute_princess_v4.webp",
    story: "大陸全土を束ねる聖なる帝国の皇女。気品あふれる立ち振る舞いと民を想う温かな慈愛の心を兼ね備え、どんな暗黒の時代でも人々の希望の光であり続ける。その身に宿す王家の加護は万病を退け、彼女が微笑むだけで傷ついた戦士たちの魂はたちまち癒やされる。"
  },
  {
    id: "CHRA_020",
    gachaItemId: "rich_knight",
    name: "暗黒騎士",
    title: "黒炎を纏う孤高の復讐者",
    rarity: "超激レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/knight.webp",
    story: "禁忌の黒炎を宿す重装甲の大剣士。かつて国を裏切られた復讐のために闇の力を受け入れたが、その魂の奥底には弱者を守る誇り高き騎士の信念が今なお静かに燃え盛っている。闇に飲まれることなく己の刃を制御し、悪しき魔の軍勢を影から狩り続ける。"
  },
  {
    id: "CHRA_021",
    gachaItemId: "rich_cyborg",
    name: "サイボーグ",
    title: "未来より来たりし機甲兵",
    rarity: "超激レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/cyborg.webp",
    story: "超未来のテクノロジーによって身体を機械化された超戦士。光学バイザーと高出力レーザー砲を駆使し、冷徹かつ正確無比な計算で脅威を排除する。失われた人間の心と記憶を少しずつ取り戻しつつあり、有機生命体の持つ「優しさ」の意味を探究している。"
  },
  {
    id: "CHRA_022",
    gachaItemId: "rich_angel",
    name: "エンジェル",
    title: "天界より舞い降りた幼き使徒",
    rarity: "超激レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/cute_angel_v4.webp",
    story: "天界より地上へ遣わされた大天使の幼き使徒。黄金に輝く聖なる光輪と純白の羽を持ち、祈りを捧げる者に天上の幸福と癒やしをもたらす。天真爛漫な笑顔で仲間の戦意を高め、その聖なる歌声は邪悪な闇の瘴気を瞬く間に浄化して光の結晶へと変える。"
  },
  {
    id: "CHRA_023",
    gachaItemId: "rich_magical",
    name: "魔法少女",
    title: "星屑のステッキ持つ愛の魔導使い",
    rarity: "超激レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/cute_magical_v4.webp",
    story: "星のステッキを手にした愛と正義の魔導少女。キラキラと輝く星魔法を自在に操り、悪しき魔物たちを鮮やかに退治する。夢と勇気を信じる心が彼女の無限の魔力の源となっており、絶体絶命の危機でも決して笑顔を絶やさず奇跡の大逆転を起こす。"
  },
  {
    id: "CHRA_024",
    gachaItemId: "rich_cool_wolf",
    name: "孤高の狼",
    title: "雪嶺を駆ける白銀の牙",
    rarity: "激レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/cool_wolf.webp",
    story: "銀嶺の雪山を単独で縄張りとする白銀の狼戦士。群れることを嫌い、自らの牙と爪のみを頼りに過酷な荒野を生き抜いてきた。一度認めた主には命を賭して尽くす不屈の忠誠心を持ち、吹雪の中で誰よりも鋭い嗅覚で危険を察知する。"
  },
  {
    id: "CHRA_025",
    gachaItemId: "rich_cool_griffin",
    name: "グリフォン",
    title: "霊峰を守護する空の王者",
    rarity: "激レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/cool_griffin.webp",
    story: "獅子の肉体と鷲の翼を併せ持つ天空の守護獣。峻険な霊峰の頂に巣を作り、聖域を侵す邪悪な者を鋭い嘴と鉤爪で急降下急襲する。高貴な魂を持ち、真の勇気を示した誇り高き冒険者には自らの背に乗る栄誉を許すという。"
  },
  {
    id: "CHRA_026",
    gachaItemId: "rich_fairy",
    name: "フェアリー",
    title: "妖精郷に踊る緑のいたずら精霊",
    rarity: "激レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/cute_fairy_v4.webp",
    story: "巨木の洞に広がる妖精郷に暮らす風の精霊。透き通る羽で花から花へと軽やかに飛び交い、妖精の粉で旅人の怪我を癒やす。好奇心旺盛で、人間の文明や古代の文字に並々ならぬ興味を示し、いつも珍しいアイテムを探し求めている。"
  },
  {
    id: "CHRA_027",
    gachaItemId: "rich_mermaid",
    name: "マーメイド",
    title: "海底神殿の秘宝を守る海姫",
    rarity: "激レア",
    gachaName: "💎 リッチガチャ1",
    gachaTabId: "rich",
    seriesId: "rich1",
    seriesName: "レジェンド・クロニクル",
    icon: "/avatars/cute_mermaid_v4.webp",
    story: "エメラルドグリーンの大海原を優雅に泳ぐ深海の人魚。海流と水流を操る古代魔法の継承者であり、沈没船に眠る失われた秘宝を守護している。月夜の晩に岩礁で美しい調べを奏で、航海者たちの安全を見守り続けている。"
  },

  // ==========================================
  // ✨ リッチガチャ2 シリーズ (24体)
  // ==========================================
  {
    id: "CHRA_028",
    gachaItemId: "神レア_漆黒の魔王軍将軍",
    name: "漆黒の魔王軍将軍",
    title: "魔界を統べる不敗の剣豪",
    rarity: "神レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/神レア_漆黒の魔王軍将軍.webp",
    story: "魔界四天王の筆頭にして、数百万の魔族軍団を統率する不敗の武人。漆黒の重鎧からは死の瘴気が立ち込め、振るう大剣は空間ごと切り裂く。武門の礼節を重んじ、小細工を嫌い強敵との一騎打ちを何よりも望む誇り高き覇者。"
  },
  {
    id: "CHRA_029",
    gachaItemId: "神レア_終焉の魔王",
    name: "終焉の魔王",
    title: "世界を混沌に沈める絶対君主",
    rarity: "神レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/神レア_終焉の魔王.webp",
    story: "幾重もの封印を破り現世に降臨した混沌と滅びの絶対君主。圧倒的な暗黒魔力で世界の理を捻じ曲げ、すべてを無へと還そうとする。その深淵なる瞳に見つめられた者は永遠の悪夢に囚われ、自我を失い配下と化してしまう。"
  },
  {
    id: "CHRA_030",
    gachaItemId: "神レア_聖なるホワイトドラゴン",
    name: "聖なるホワイトドラゴン",
    title: "雪嶺の頂に眠る純白の聖龍",
    rarity: "神レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/神レア_聖なるホワイトドラゴン.webp",
    story: "雪嶺の最高峰「アイシクル・ピーク」の頂に鎮座する聖龍。吐き出す白銀のブレスは万物の邪念を凍てつかせ浄化する。古の英雄と交わした「世界が闇に包まれし時、再び飛翔せん」という盟約を守り、悠久の眠りから覚醒した。"
  },
  {
    id: "CHRA_031",
    gachaItemId: "神レア_虚無の使者・カオスエージェント",
    name: "虚無の使者・カオスエージェント",
    title: "時空の歪みを紡ぐ特異点",
    rarity: "神レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/神レア_虚無の使者・カオスエージェント.webp",
    story: "多次元宇宙の狭間「ヴォイド」より飛来した謎多き異形の執行官。時空の歪みを操り、世界の因果律を書き換える使命を帯びる。その冷徹な仮面の下の素顔を知る者は全宇宙に存在せず、神々すらもその動向を警戒している。"
  },
  {
    id: "CHRA_032",
    gachaItemId: "神レア_虚空の堕天使",
    name: "虚空の堕天使",
    title: "神の光を捨てし黒翼の反逆者",
    rarity: "神レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/神レア_虚空の堕天使.webp",
    story: "神への反逆により天界を追放され、黒き翼となった元筆頭熾天使。絶望と虚無の魔力を束ね、偽りの平穏を享受する地上界に裁きの雷を落とす。冷酷な破壊者として振る舞うが、かつての聖なる記憶に今なお苦悩している。"
  },
  {
    id: "CHRA_033",
    gachaItemId: "超激レア_大賢者",
    name: "大賢者",
    title: "千年を生きる生ける叡智の伝説",
    rarity: "超激レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/超激レア_大賢者.webp",
    story: "千年の時を生きて世界中の古文書と魔導書を読破した知識の生ける伝説。手にした星杖から放たれる属性魔法は天変地異に匹敵する威力を誇る。世界の滅亡を回避すべく、各地で才能ある若き勇者たちを密かに見守り導く。"
  },
  {
    id: "CHRA_034",
    gachaItemId: "超激レア_異次元の魔法使い",
    name: "異次元の魔法使い",
    title: "並行世界を旅する次元跳躍者",
    rarity: "超激レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/超激レア_異次元の魔法使い.webp",
    story: "異なる並行世界を渡り歩く次元跳躍の魔導使い。奇抜な帽子と次元ゲートを開く鍵杖を手に、歴史の改変を目論む時間犯罪者を追跡している。飄々とした性格だが戦闘能力は超一流で、異世界の未知なる魔導兵器を使いこなす。"
  },
  {
    id: "CHRA_035",
    gachaItemId: "超激レア_雷光の精霊・サンダービースト",
    name: "雷光の精霊・サンダービースト",
    title: "稲妻を纏う神速の雷獣",
    rarity: "超激レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/超激レア_雷光の精霊・サンダービースト.webp",
    story: "激しい雷雲と共に大地に舞い降りる金色の雷獣。全身に数百万ボルトの稲妻を纏い、超音速で戦場を駆け巡る。雷神の使いとして崇められ、その咆哮は雨雲を呼び乾いた大地を潤すと伝えられている。"
  },
  {
    id: "CHRA_036",
    gachaItemId: "激レア_天才魔導士",
    name: "天才魔導士",
    title: "数式魔法を操る最年少魔術師",
    rarity: "激レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/激レア_天才魔導士.webp",
    story: "弱冠十歳にして王立魔導院の最高位に登りつめた神童。常人には理解不能な超高度な数式魔法を展開し、あらゆる敵の防御結界を一瞬で分解・無効化する。生意気な口を利くが仲間思いで、ピンチの時には誰よりも頼りになる。"
  },
  {
    id: "CHRA_037",
    gachaItemId: "激レア_狂気の道化師",
    name: "狂気の道化師",
    title: "幻影と嘲笑のサーカス怪人",
    rarity: "激レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/激レア_狂気の道化師.webp",
    story: "トランプとナイフを華麗に操るサーカス団の怪人。笑い声と共に敵を幻惑し、神出鬼没のトリッキーな動きで戦場を混乱の渦に巻き込む。その道化の笑みの裏には深い悲しみの過去が隠されており、真実を見抜く者にのみ心を開く。"
  },
  {
    id: "CHRA_038",
    gachaItemId: "激レア_蒼き魔法剣士",
    name: "蒼き魔法剣士",
    title: "蒼炎刃を振るう若き剣豪",
    rarity: "激レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/激レア_蒼き魔法剣士.webp",
    story: "刀身に氷と風の魔力を纏わせる蒼炎流剣術の若き継承者。静水のごとき精神統一から繰り出される神速の抜刀術は、一瞬で敵の装甲を凍結させ両断する。ストイックに武の道を追求し、悪を断つために日々剣技を磨く。"
  },
  {
    id: "CHRA_039",
    gachaItemId: "激レア_闇の精霊使い",
    name: "闇の精霊使い",
    title: "漆黒の影と絆を結ぶ術士",
    rarity: "激レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/激レア_闇の精霊使い.webp",
    story: "宵闇に棲まう影の精霊たちと契約を結んだ孤高の召喚術士。自らの影を自在に変形させて武器や盾とし、敵の足元から奇襲を仕掛ける。闇属性を操るが心根は非常に温かく、困っている人を放っておけない義理堅い性格。"
  },
  {
    id: "CHRA_040",
    gachaItemId: "レア_エルフの森の射手",
    name: "エルフの森の射手",
    title: "千年樹を守護する神射手",
    rarity: "レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/レア_エルフの森の射手.webp",
    story: "千年樹の原生林を守護するエルフ族の警備隊長。風を味方につけた弓の腕前は、葉の落ちる軌道すら射抜く。侵入者には冷徹だが、森の生態系を尊ぶ冒険者には温かいもてなしをし、旅の道案内を買って出る。"
  },
  {
    id: "CHRA_041",
    gachaItemId: "レア_呪われし死霊騎士",
    name: "呪われし死霊騎士",
    title: "悔恨の亡霊となりし旧国の忠臣",
    rarity: "レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/レア_呪われし死霊騎士.webp",
    story: "古代王国の滅亡時に王女を守り抜けず、悔恨からアンデッドとして蘇った亡霊騎士。錆びた甲冑と怨嗟の剣を手に、自らを討ち果たして成仏させてくれる真の強者を求め、廃墟となった王城を彷徨い続けている。"
  },
  {
    id: "CHRA_042",
    gachaItemId: "レア_氷結の魔女",
    name: "氷結の魔女",
    title: "絶対零度を操る白銀の術者",
    rarity: "レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/レア_氷結の魔女.webp",
    story: "永久凍土の氷城に住まうクールな氷系魔導使い。周囲の空気を絶対零度まで低下させ、氷柱の雨を降らせる。感情を表に出すのが苦手で冷徹に見られがちだが、温かいココアを飲む時だけ少し頬を緩める可愛らしい一面がある。"
  },
  {
    id: "CHRA_043",
    gachaItemId: "レア_蜘蛛の女戦士",
    name: "蜘蛛の女戦士",
    title: "深淵の巣穴を守護する蜘蛛人族の闘姫",
    rarity: "レア",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/レア_蜘蛛の女戦士.webp",
    story: "迷宮の最深部に巣食う蜘蛛人族（アラクネ）の誇り高き女戦士。背から伸びる鋭利な節足と、鋼のように強靭な粘糸を自在に操り、暗闇から音もなく獲物を絡め取る。冷徹な狩人として恐れられているが、巣に入り込んだ迷子を糸のハンモックで優しく介抱して出口まで導くなど、慈悲深い一面も持ち合わせている。"
  },
  {
    id: "CHRA_044",
    gachaItemId: "ノーマル_堅牢の山岳ドワーフ",
    name: "堅牢の山岳ドワーフ",
    title: "大岩をも砕く槌持つ頑固鍛冶師",
    rarity: "ノーマル",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/ノーマル_堅牢の山岳ドワーフ.webp",
    story: "鉱山都市の地下工房で鍛冶と戦いに明け暮れる頑固一徹の戦士。自ら鍛え上げた頑丈な槌と重鎧を愛用し、どんな衝撃にもビクともしない。酒と上質な鉱石の話になると途端に上機嫌になり、語り明かす。"
  },
  {
    id: "CHRA_045",
    gachaItemId: "ノーマル_堕落した聖騎士",
    name: "堕落した聖騎士",
    title: "聖印を捨て放浪する元エリート",
    rarity: "ノーマル",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/ノーマル_堕落した聖騎士.webp",
    story: "教団の不正と欺瞞に絶望し、聖印を捨てて野に下った元エリート騎士。身なりは荒れているが剣技の鋭さは健在で、真の正義とは何かを自問自答しながら、路地裏の弱者を人知れず守る放浪の旅を続けている。"
  },
  {
    id: "CHRA_046",
    gachaItemId: "ノーマル_嵐を呼ぶハーピー・リーダー",
    name: "嵐を呼ぶハーピー・リーダー",
    title: "断崖を支配する突風の女王",
    rarity: "ノーマル",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/ノーマル_嵐を呼ぶハーピー・リーダー.webp",
    story: "峡谷の断崖に巣食うハーピー族の誇り高きリーダー。翼を羽ばたかせて突風を巻き起こし、侵入者を崖下へと吹き飛ばす。縄張り意識が非常に強いが、義理堅く一度交わした約束は命がけで守り抜く。"
  },
  {
    id: "CHRA_047",
    gachaItemId: "ノーマル_災厄の双頭キマイラ",
    name: "災厄の双頭キマイラ",
    title: "炎と毒を吐き出す古代の門番",
    rarity: "ノーマル",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/ノーマル_災厄の双頭キマイラ.webp",
    story: "獅子と竜の二つの首を持つ凶暴な合成獣。火炎と毒霧の異なる属性ブレスを同時に吐き出す。気性は荒いが知能が高く、古代遺跡の宝物庫を守護する門番としての誇り高き使命を忠実に果たしている。"
  },
  {
    id: "CHRA_048",
    gachaItemId: "ノーマル_炎獄の魔戦士",
    name: "炎獄の魔戦士",
    title: "マグマより生まれし熱血巨漢",
    rarity: "ノーマル",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/ノーマル_炎獄の魔戦士.webp",
    story: "火山帯のマグマから生まれた魔界の肉体派戦士。全身が常に赤く発熱しており、巨大な炎の大剣を力任せに叩きつける。好戦的で単純な性格だが、卑怯な手を嫌い真っ向勝負を尊ぶ潔い魂を持つ。"
  },
  {
    id: "CHRA_049",
    gachaItemId: "ノーマル_猛火のサラマンダーマン",
    name: "猛火のサラマンダーマン",
    title: "耐火鱗を誇る灼熱の拳士",
    rarity: "ノーマル",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/ノーマル_猛火のサラマンダーマン.webp",
    story: "火竜の血を引く爬虫類系の亜人戦士。高熱の業火をものともしない耐火鱗を持ち、灼熱の拳で連続攻撃を叩き込む。豪快な性格で、熱い溶岩風呂に入ることと激辛料理を食べ歩くことが無上の楽しみ。"
  },
  {
    id: "CHRA_050",
    gachaItemId: "ノーマル_荒野の大剣豪",
    name: "荒野の大剣豪",
    title: "砂塵の果てより来たりし無頼漢",
    rarity: "ノーマル",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/ノーマル_荒野の大剣豪.webp",
    story: "東方の果てから武者修行のために渡ってきたさすらいの剣客。風化の進む荒野で無数の辻斬りや賞金首を倒してきた。無口で無骨だが、弱き者を助ける義侠心に溢れ、報酬は一杯の水と飯だけで満足する。"
  },
  {
    id: "CHRA_051",
    gachaItemId: "ノーマル_近衛兵リーダー槍使い",
    name: "近衛兵リーダー槍使い",
    title: "王都の正門を守護する若き指揮官",
    rarity: "ノーマル",
    gachaName: "✨ リッチガチャ2",
    gachaTabId: "rich2",
    seriesId: "rich2",
    seriesName: "覇王と混沌の叙事詩",
    icon: "/images/gacha2/ノーマル_近衛兵リーダー槍使い.webp",
    story: "王宮の正門を守る精鋭近衛隊の若き隊長。長大なハルバードを自在に繰り出し、鉄壁の陣形を敷いて王都の平和を死守する。真面目で規則に厳しいが部下からの信頼は非常に厚く、街の子どもたちからも親しまれている。",
    type: "avatar"
  },

  // ==========================================
  // 🎀 ふわふわ装備シリーズ (15種)
  // ==========================================
  {
    id: "EQ_LADIES_001",
    gachaItemId: "eq_ladies_angel_tiara",
    name: "天使の羽根のティアラ",
    title: "天界より舞い降りし聖なる加護",
    rarity: "神レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/天使の羽根のティアラ.webp",
    story: "天界の最高位天使の翼から抜け落ちた純白の羽根を織り込んで作られた伝説のティアラ。身につけた者の精神を浄化し、あらゆる悪意や呪いから守護する絶大な聖なる光を放ち続ける。",
    type: "equipment",
    category: "head"
  },
  {
    id: "EQ_LADIES_002",
    gachaItemId: "eq_ladies_stardust_staff",
    name: "星屑のキラキラスタッフ",
    title: "夜空の瞬きを宿す星彩の魔導杖",
    rarity: "神レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/星屑のキラキラスタッフ.webp",
    story: "流れ星の破片と銀河の輝きを閉じ込めた究極の魔法杖。一振りすれば無数の星屑がキラキラと舞い散り、周囲の空間全体に強力な星間魔法を展開して敵を魅了し打ち倒す。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_LADIES_003",
    gachaItemId: "eq_ladies_rose_rapier",
    name: "バラの舞踏レイピア",
    title: "真紅の棘が舞い散る華麗なる細剣",
    rarity: "超激レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/バラの舞踏レイピア.webp",
    story: "満開の薔薇の美しさと鋭利な棘の危険性を併せ持つ細剣。舞踏のように優雅な剣戟から繰り出される突きは、花びらの残像とともに敵の急所を一瞬で貫く。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_LADIES_004",
    gachaItemId: "eq_ladies_mermaid_earring",
    name: "マーメイドの真珠イヤリング",
    title: "深海の王女が愛した神秘の宝飾",
    rarity: "超激レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/マーメイドの真珠イヤリング.webp",
    story: "深海都市アトランティスの人魚姫が身につけていた秘宝の耳飾り。水のように澄んだ真珠が耳元でかすかに波音を奏で、身につける者に海の精霊の加護を与える。",
    type: "equipment",
    category: "accessory"
  },
  {
    id: "EQ_LADIES_005",
    gachaItemId: "eq_ladies_ribbon_tact",
    name: "リボンと花のタクト",
    title: "魔法少女が紡ぐ夢と希望の指揮棒",
    rarity: "超激レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/リボンと花のタクト.webp",
    story: "ピンクのリボンと可憐な花々で装飾された魔法少女のタクト。空中に光の軌跡を描きながら振るうことで、仲間の士気を極限まで高め、奇跡の魔法を発動させる。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_LADIES_006",
    gachaItemId: "eq_ladies_fallen_lace",
    name: "堕天使のレース",
    title: "漆黒の宵闇を纏う禁忌の羽衣",
    rarity: "超激レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/堕天使のレース.webp",
    story: "かつて天界を追放された誇り高き天使の翼の残り香から編み上げられた黒レースの羽衣。身につけた者の周囲に静寂な闇の帳を張り巡らせ、あらゆる探知を無効化する。",
    type: "equipment",
    category: "wings"
  },
  {
    id: "EQ_LADIES_007",
    gachaItemId: "eq_ladies_moon_necklace",
    name: "月と星のネックレス",
    title: "夜空の静寂と天体の魔導ペンダント",
    rarity: "超激レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/月と星のネックレス.webp",
    story: "三日月と金色の星が寄り添うロマンチックな首飾り。夜の静けさとともに持ち主の集中力を研ぎ澄まし、魔力の回復速度を飛躍的に高める効果がある。",
    type: "equipment",
    category: "accessory"
  },
  {
    id: "EQ_LADIES_008",
    gachaItemId: "eq_ladies_bear_grimoire",
    name: "クマさんの抱き枕魔導書",
    title: "もふもふの温もりに眠る古代魔導",
    rarity: "激レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/クマさんの抱き枕魔導書.webp",
    story: "可愛らしいテディベアの形をした不思議な魔導書。抱きしめて眠ると、夢の中で古代の賢者から強力な魔法の手ほどきを受けることができる。",
    type: "equipment",
    category: "accessory"
  },
  {
    id: "EQ_LADIES_009",
    gachaItemId: "eq_ladies_pastel_gauntlet",
    name: "スイーツデコのパステルガントレット",
    title: "お菓子とホイップの甘美なる手甲",
    rarity: "激レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/スイーツデコのパステルガントレット.webp",
    story: "パステルカラーのクリームとフルーツデコレーションで固められた手甲。見た目は完全にスイーツだが、硬化魔法により岩をも砕く打撃力を誇る。",
    type: "equipment",
    category: "accessory"
  },
  {
    id: "EQ_LADIES_010",
    gachaItemId: "eq_ladies_heart_shield",
    name: "ハートのフリルシールド",
    title: "愛と友情の力で弾くピンクの盾",
    rarity: "激レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/ハートのフリルシールド.webp",
    story: "ハート型のエンブレムにフリルをあしらったキュートな盾。持ち主の純粋な想いをエネルギーに変換し、敵の物理攻撃を軽やかに跳ね返す。",
    type: "equipment",
    category: "shield"
  },
  {
    id: "EQ_LADIES_011",
    gachaItemId: "eq_ladies_sunflower_flute",
    name: "ひまわりのビースト笛",
    title: "太陽の音色で聖獣を呼ぶ魔法笛",
    rarity: "レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/ひまわりのビースト笛.webp",
    story: "ひまわりの花を模した明るい音色の笛。吹くと陽気なメロディが広がり、森の小さな魔獣たちが冒険を助けに駆け寄ってくる。",
    type: "equipment",
    category: "accessory"
  },
  {
    id: "EQ_LADIES_012",
    gachaItemId: "eq_ladies_candy_sword",
    name: "キャンディポップの大剣",
    title: "甘くてカラフルな超重量級ブレード",
    rarity: "レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/キャンディポップの大剣.webp",
    story: "カラフルな渦巻きキャンディをそのまま大剣にしたような装備。甘い香りを漂わせながら敵に大打撃を与える。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_LADIES_013",
    gachaItemId: "eq_ladies_cat_gloves",
    name: "モフモフ猫パンチグローブ",
    title: "肉球の柔らかさと鋭い爪の秘密",
    rarity: "レア",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/モフモフ猫パンチグローブ.webp",
    story: "最高級の猫毛で作られたふわふわの手袋。肉球部分は驚くほど柔らかいが、猫パンチを繰り出すと鋭い風圧波が発生する。",
    type: "equipment",
    category: "accessory"
  },
  {
    id: "EQ_LADIES_014",
    gachaItemId: "eq_ladies_strawberry_cap",
    name: "いちごのショートケーキキャップ",
    title: "甘酸っぱい幸せを乗せたベレー帽",
    rarity: "ノーマル",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/いちごのショートケーキキャップ.webp",
    story: "本物のショートケーキそっくりに仕立てられた可愛い帽子。かぶるだけで気分がウキウキし、冒険の足取りが軽くなる。",
    type: "equipment",
    category: "head"
  },
  {
    id: "EQ_LADIES_015",
    gachaItemId: "eq_ladies_bunny_bag",
    name: "うさ耳の夢かわリュック",
    title: "ぴょこんと跳ねるうさ耳ポシェット",
    rarity: "ノーマル",
    gachaName: "🎀 ふわふわ装備ガチャ♡",
    gachaTabId: "rich_ladies_equipment",
    seriesId: "ladies_eq",
    seriesName: "ふわふわ装備",
    icon: "/images/gacha_equipment_ladies_webp/うさ耳の夢かわリュック.webp",
    story: "長いうさ耳が揺れるパステル調のリュックサック。冒険に必要な回復薬やお菓子がたっぷり入るお気に入りアイテム。",
    type: "equipment",
    category: "accessory"
  },

  // ==========================================
  // 🛡️ リッチ装備シリーズ (13種)
  // ==========================================
  {
    id: "EQ_RICH_001",
    gachaItemId: "eq_rich_excalibur",
    name: "聖剣エクスカリバー（極）",
    title: "眩き黄金の光を放つ伝説の至高剣",
    rarity: "神レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/神レア_聖剣エクスカリバー.webp",
    story: "選ばれし勇者のみが抜くことを許される伝説の聖剣。刀身から放たれる黄金の閃光は、大地を覆うあらゆる闇を切り裂き、勝利の栄光をもたらす。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_RICH_002",
    gachaItemId: "eq_rich_angel_robe",
    name: "天使の翼衣",
    title: "天上の加護を宿す純白の羽衣",
    rarity: "超激レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/超激レア_天使の翼衣.webp",
    story: "天使の羽毛で織り上げられた神聖なるローブ。纏う者の体をふわりと宙に浮かべ、あらゆる邪悪な攻撃から守護する。",
    type: "equipment",
    category: "wings"
  },
  {
    id: "EQ_RICH_003",
    gachaItemId: "eq_rich_flame_grimoire",
    name: "炎帝の魔導書",
    title: "獄炎の禁術が刻まれし灼熱の聖典",
    rarity: "超激レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/超激レア_炎帝の魔導書.webp",
    story: "古の炎帝が編纂した禁断の魔導書。ページを開けば紅蓮の業火が渦巻き、周囲の敵を一瞬にして灰燼に帰す破壊力を宿す。",
    type: "equipment",
    category: "accessory"
  },
  {
    id: "EQ_RICH_004",
    gachaItemId: "eq_rich_flame_gauntlet",
    name: "爆炎の籠手",
    title: "拳に爆砕の炎を灯す真紅の手甲",
    rarity: "超激レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/超激レア_爆炎の籠手.webp",
    story: "マグマの熱を封じ込めた真紅の籠手。放つ拳の一撃ごとに爆裂する火柱が立ち昇り、堅固な城壁をも打ち砕く。",
    type: "equipment",
    category: "accessory"
  },
  {
    id: "EQ_RICH_005",
    gachaItemId: "eq_rich_dark_helm",
    name: "闇夜の漆黒兜",
    title: "暗黒街を統べる覇王の威圧兜",
    rarity: "超激レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/超激レア_闇夜の漆黒兜.webp",
    story: "闇の覇王が戦場で着用した漆黒の兜。装着者の瞳に冷徹な威圧感を宿らせ、対峙する敵の闘志を瞬時に奪い去る。",
    type: "equipment",
    category: "head"
  },
  {
    id: "EQ_RICH_006",
    gachaItemId: "eq_rich_gram_sword",
    name: "魔剣グラム",
    title: "巨竜をも一刀両断する破竜の魔刃",
    rarity: "超激レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/超激レア_魔剣グラム.webp",
    story: "北欧の英雄が竜を討伐する際に振るった名高き大剣。竜の硬質な鱗すら紙のように切り裂く圧倒的な切断力を誇る。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_RICH_007",
    gachaItemId: "eq_rich_aegis_shield",
    name: "守護神のイージス盾",
    title: "森羅万象の攻撃を拒絶する神域の防壁",
    rarity: "激レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/激レア_守護神のイージス盾.webp",
    story: "神々の鍛冶師が鍛え上げた鉄壁の大盾。あらゆる属性魔法や物理攻撃を反射し、持ち主を完璧に守護する。",
    type: "equipment",
    category: "shield"
  },
  {
    id: "EQ_RICH_008",
    gachaItemId: "eq_rich_sage_staff",
    name: "賢者の星杖",
    title: "星界の叡智と膨大なるマナの宿る杖",
    rarity: "激レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/激レア_賢者の星杖.webp",
    story: "千年の修行を積んだ大賢者が愛用した杖。先端の星晶石が絶え間なくマナを供給し、高度な魔導の行使を助ける。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_RICH_009",
    gachaItemId: "eq_rich_wind_bow",
    name: "風神の戦弓",
    title: "大気を裂き風の刃を放つ神弓",
    rarity: "激レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/激レア_風神の戦弓.webp",
    story: "疾風の精霊王が授けた緑なす戦弓。矢を番えて放てば旋風を巻き起こし、超遠距離から正確無比に標的を射抜く。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_RICH_010",
    gachaItemId: "eq_rich_dragon_scale",
    name: "神龍の鱗鎧",
    title: "古龍の堅甲で仕立てられた堅牢なる鎧",
    rarity: "レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/レア_神龍の鱗鎧.webp",
    story: "古代の神龍から剥落した鱗を繋ぎ合わせて作られた防具。並の刃物では傷一つ付けることができない高い防御力を誇る。",
    type: "equipment",
    category: "shield"
  },
  {
    id: "EQ_RICH_011",
    gachaItemId: "eq_rich_overlord_axe",
    name: "覇王の戦斧",
    title: "一振りで大地を砕く狂乱の大斧",
    rarity: "レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/レア_覇王の戦斧.webp",
    story: "幾多の戦場を制覇した覇王の巨大な斧。その重厚な刀身から繰り出される回転斬撃は敵陣を一撃で崩壊させる。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_RICH_012",
    gachaItemId: "eq_rich_dark_blades",
    name: "闇夜の双刃",
    title: "月影に潜み敵を刈り取る暗殺双剣",
    rarity: "レア",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/レア_闇夜の双刃.webp",
    story: "光を反射しない特殊な鉱石で鍛えられた一対の短剣。闇夜に溶け込み、音もなく敵の背後に忍び寄る。",
    type: "equipment",
    category: "weapon"
  },
  {
    id: "EQ_RICH_013",
    gachaItemId: "eq_rich_longinus",
    name: "竜槍ロンギヌス",
    title: "竜の闘気を宿す深紅の長槍",
    rarity: "ノーマル",
    gachaName: "🛡️ 装備品リッチガチャ",
    gachaTabId: "rich_equipment",
    seriesId: "rich_eq",
    seriesName: "リッチ装備",
    icon: "/images/gacha_equipment/ノーマル_竜槍ロンギヌス.webp",
    story: "竜の骨から削り出された美しい長槍。突進とともに竜の咆哮のような風切り音を立て、獲物を仕留める。",
    type: "equipment",
    category: "weapon"
  }
];

export function getAvatarEncyclopediaEntry(idOrNameOrIcon: string): AvatarEncyclopediaEntry | undefined {
  if (!idOrNameOrIcon) return undefined;
  return avatarEncyclopediaList.find(e => 
    e.id === idOrNameOrIcon ||
    e.gachaItemId === idOrNameOrIcon ||
    e.name === idOrNameOrIcon ||
    e.icon === idOrNameOrIcon ||
    idOrNameOrIcon.includes(e.name) ||
    e.name.includes(idOrNameOrIcon)
  );
}

export function getAvatarEncyclopediaBySeries(seriesId: string): AvatarEncyclopediaEntry[] {
  return avatarEncyclopediaList.filter(e => e.seriesId === seriesId);
}
